// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dailog: typeof import('./src/components/scene2/dailog.vue')['default']
    Dannmaku: typeof import('./src/components/scene1/dannmaku.vue')['default']
    Flowy: typeof import('./src/components/scene2/flowy.vue')['default']
    Gravity: typeof import('./src/components/scene1/Gravity.vue')['default']
    Gravity3D: typeof import('./src/components/trashcan/gravity3D.vue')['default']
    Intor: typeof import('./src/components/scene3/intor.vue')['default']
    MidiPlayer: typeof import('./src/components/trashcan/midiPlayer.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NModal: typeof import('naive-ui')['NModal']
    OffscreenCanvas: typeof import('./src/components/trashcan/offscreenCanvas.vue')['default']
    PopChat: typeof import('./src/components/scene3/intors/popChat.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    S2bg: typeof import('./src/components/scene2/s2bg.vue')['default']
    Sanhua: typeof import('./src/components/scene3/sanhua.vue')['default']
    ThreejsView: typeof import('./src/components/trashcan/threejsView.vue')['default']
    Typed: typeof import('./src/components/scene1/typed.vue')['default']
  }
}
