// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dailog: typeof import('./src/components/scene2/dailog.vue')['default']
    Dannmaku: typeof import('./src/components/scene1/dannmaku.vue')['default']
    Gravity: typeof import('./src/components/scene1/Gravity.vue')['default']
    Gravity3D: typeof import('./src/components/gravity3D.vue')['default']
    MidiPlayer: typeof import('./src/components/midiPlayer.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    OffscreenCanvas: typeof import('./src/components/offscreenCanvas.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    S2bg: typeof import('./src/components/scene2/s2bg.vue')['default']
    ThreejsView: typeof import('./src/components/threejsView.vue')['default']
    Typed: typeof import('./src/components/scene1/typed.vue')['default']
  }
}
